name: Fetch Spreadsheet Data

on:
  schedule:
    - cron: "0 0 * * *"  # daily 00:00 UTC
  workflow_dispatch:  # Manual start possible

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Create .env file
        run: |
          echo "COMMUNITY_SPREADSHEET_ID=${{ secrets.COMMUNITY_SPREADSHEET_ID }}" >> backend/.env
          echo "SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }}" >> backend/.env
          echo "API_KEY=${{ secrets.API_KEY }}" >> backend/.env

      - name: Save Firebase Credentials
        run: |
          echo '${{ secrets.FIREBASE_PRIVATE_KEY }}' | jq '.' > backend/serviceAccountKey.json
          ls -lah backend  # Check whether the file exists
          cat backend/serviceAccountKey.json  # Debugging: Output file content
  

      - name: Fetch & Push Data in Firestore
        run: |
          cd backend
          node fetch.js
