name: Fetch and Sync Spreadsheet Data

on:
  schedule:
    - cron: "0 0 * * *"  # daily at 00:00 UTC
  workflow_dispatch:  # Manual execution possible

jobs:
  fetch-and-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Create .env file
        run: |
          echo "COMMUNITY_SPREADSHEET_ID=${{ secrets.COMMUNITY_SPREADSHEET_ID }}" >> backend/.env
          echo "SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }}" >> backend/.env
          echo "API_KEY=${{ secrets.API_KEY }}" >> backend/.env

      - name: Save Firebase Credentials
        run: |
          echo '${{ secrets.FIREBASE_CREDENTIALS }}' > backend/serviceAccountKey.json
          sed -i 's/\\n/\n/g' backend/serviceAccountKey.json  # Newline fix

      - name: Fetch Community Spreadsheet Data and Push to Firestore
        run: |
          cd backend
          node fetch.js

      - name: Sync Stock Data to Firestore
        run: |
          cd backend
          node index.js