name: Fetch Spreadsheet Data

on:
  schedule:
    - cron: '0 0 * * *'  # daily at 00:00 UTC
  workflow_dispatch:  # Manual execution possible

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Save service account key
        run: echo "${{ secrets.FIREBASE_PRIVATE_KEY }}" > ./backend/serviceAccountKey.json

      - name: Fetch & Push Data in Firestore
        env:
          COMMUNITY_SPREADSHEET_ID: ${{ secrets.COMMUNITY_SPREADSHEET_ID }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          cd backend
          node fetch.js

