name: Sync Stock Data From Spreadsheet to Firebase

on:
  schedule:
    - cron: '0 0 * * *'  # täglich um 00:00 UTC
  workflow_dispatch:  # Manuelle Ausführung möglich

jobs:
  sync-stocks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Check Environment Variables
        run: |
          if [ -z "${{ secrets.FIREBASE_PRIVATE_KEY }}" ]; then
            echo "❌ FIREBASE_PRIVATE_KEY ist nicht gesetzt!"
            exit 1
          fi
          if [ -z "${{ secrets.SPREADSHEET_ID }}" ]; then
            echo "❌ SPREADSHEET_ID ist nicht gesetzt!"
            exit 1
          fi
          if [ -z "${{ secrets.API_KEY }}" ]; then
            echo "❌ API_KEY ist nicht gesetzt!"
            exit 1
          fi

      - name: Sync Spreadsheet Data to Firestore
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          API_KEY: ${{ secrets.API_KEY }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        run: |
          cd backend
          node index.js
